name: 'Podcast Generator'
author: 'Ola Halawani'
description: 'Generates a feed for a podcast'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'git-branch'
  color: 'green'
inputs:
  email: 
    description: "The committer's email address"
    required: true
    default: ${{ github.actor }}@localhost 
  name:
    description: "The committer's name"
    required: true
    default: ${{ github.actor }} 
container:
  image: ghcr.io/owner/image
  credentials:
     username: ${{ github.actor }}
     password: ${{ secrets.ghcr_token }}
